version: '3.7'

# This docker-compose file brings up a Configuration Databse instance pointing to
# localhost for its connections to a postgres DB and the Observation Portal. You
# will want to modify the DB_* environment variables to connect to your db backend,
# and modify the OAUTH_* environment variables to contain the correct credentials for
# your Observation Portal oauth Configdb application.
services:
    nginx:
        image: nginx:1.19.0-alpine
        ports:
            - 7000:80
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - static_volume:/static
        depends_on:
            - configdb
    configdb:
        image: observatorycontrolsystem/configdb:2.1.3
        expose:
          - "7001"
        environment:
          # Note that 172.17.0.1 works for localhost on linux, but for mac you will
          # need to use `host.docker.internal` instead to point to localhost.
          - DB_HOST=172.17.0.1
          - DB_NAME=configdb
          - DB_USER=postgres
          - DB_PASS=postgres
          - DB_PORT=5432
          - SECRET_KEY=configdb_secret_key
          - OAUTH_CLIENT_ID=observation_portal_application_client_id
          - OAUTH_CLIENT_SECRET=observation_portal_application_client_secret
          - OAUTH_TOKEN_URL=http://172.17.0.1:8000/o/token/
        mem_limit: "512m"
        restart: always
        volumes:
          - static_volume:/static
        command: >
            sh -c "python manage.py migrate
            && python manage.py collectstatic --no-input
            && gunicorn --bind=0.0.0.0:7001 --worker-class=gevent --workers=4 --access-logfile=- --error-logfile=- configdb.wsgi:application"

volumes:
    static_volume:
