# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='elevation',
            field=models.IntegerField(default=0, help_text='meters'),
            preserve_default=False,
        ),
    ]
