# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0005_populate_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='schedulable',
        ),
    ]
