# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0006_remove_instrument_schedulable'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameratype',
            name='acquire_exposure_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cameratype',
            name='acquire_processing_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cameratype',
            name='config_change_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cameratype',
            name='filter_change_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cameratype',
            name='fixed_overhead_per_exposure',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='cameratype',
            name='front_padding',
            field=models.FloatField(default=90),
        ),
        migrations.AddField(
            model_name='mode',
            name='readout',
            field=models.FloatField(default=0),
        ),
    ]
