# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-30 23:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0007_add_timings'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='site',
            name='long',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='site',
            name='restart',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='site',
            name='tz',
            field=models.CharField(default='Etc/UTC', help_text='Timezone Name', max_length=64),
        ),
    ]
