# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-22 21:30
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0008_auto_20180730_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('overhead', models.FloatField()),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpticalElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200, unique=True)),
                ('schedulable', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpticalElementGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('element_change_overhead', models.FloatField(default=0)),
                ('optical_elements', models.ManyToManyField(to='hardware.OpticalElement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='camera',
            name='host',
            field=models.CharField(default='', help_text='The physical machine hostname that this camera is connected to', max_length=200),
        ),
        migrations.AddField(
            model_name='cameratype',
            name='configuration_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=None),
        ),
        migrations.AddField(
            model_name='cameratype',
            name='default_acceptability_threshold',
            field=models.FloatField(default=90.0),
        ),
        migrations.AddField(
            model_name='cameratype',
            name='max_rois',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cameratype',
            name='pixels_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cameratype',
            name='pixels_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instrument',
            name='code',
            field=models.CharField(default='', help_text='Name of the instrument', max_length=200),
        ),
        migrations.AddField(
            model_name='telescope',
            name='instrument_change_overhead',
            field=models.FloatField(default=0, help_text='The maximum amount of time it takes to switch instruments'),
        ),
        migrations.AddField(
            model_name='telescope',
            name='minimum_slew_overhead',
            field=models.FloatField(default=0, help_text='The minimum amount of time a slew can take in seconds'),
        ),
        migrations.AddField(
            model_name='telescope',
            name='serial_number',
            field=models.CharField(default='', help_text='Unique telescope serial number', max_length=50),
        ),
        migrations.AddField(
            model_name='telescope',
            name='slew_rate',
            field=models.FloatField(default=0, help_text='The rate in sec/arcsec at which the telescope slews between positions'),
        ),
        migrations.AddField(
            model_name='genericmode',
            name='camera_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modes', to='hardware.CameraType'),
        ),
        migrations.AddField(
            model_name='camera',
            name='modes',
            field=models.ManyToManyField(to='hardware.GenericMode'),
        ),
        migrations.AddField(
            model_name='camera',
            name='optical_element_groups',
            field=models.ManyToManyField(to='hardware.OpticalElementGroup'),
        ),
    ]
