# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-23 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0010_remove_camera_modes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='code',
            field=models.CharField(blank=True, default='', help_text='Name of the instrument', max_length=200),
        ),
    ]
