# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-23 22:56
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0011_auto_20190123_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeType',
            fields=[
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='camera',
            name='host',
            field=models.CharField(blank=True, default='', help_text='The physical machine hostname that this camera is connected to', max_length=200),
        ),
        migrations.AlterField(
            model_name='cameratype',
            name='configuration_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None),
        ),
        migrations.RemoveField(
            model_name='genericmode',
            name='type',
        ),
        migrations.AddField(
            model_name='genericmode',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, null=True, to='hardware.ModeType'),
        ),
    ]
