# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-01 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0012_auto_20190123_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericModeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('camera_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mode_types', to='hardware.CameraType')),
            ],
        ),
        migrations.RemoveField(
            model_name='genericmode',
            name='camera_type',
        ),
        migrations.RemoveField(
            model_name='genericmode',
            name='default',
        ),
        migrations.RemoveField(
            model_name='genericmode',
            name='type',
        ),
        migrations.AddField(
            model_name='opticalelementgroup',
            name='default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default', to='hardware.OpticalElement'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='optical_element_groups',
            field=models.ManyToManyField(blank=True, to='hardware.OpticalElementGroup'),
        ),
        migrations.AddField(
            model_name='genericmodegroup',
            name='default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default', to='hardware.GenericMode'),
        ),
        migrations.AddField(
            model_name='genericmodegroup',
            name='modes',
            field=models.ManyToManyField(to='hardware.GenericMode'),
        ),
        migrations.AddField(
            model_name='genericmodegroup',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hardware.ModeType'),
        ),
        migrations.AlterUniqueTogether(
            name='genericmodegroup',
            unique_together=set([('camera_type', 'type')]),
        ),
    ]
