# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0015_telescope_zenith_blind_spot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='state',
            field=models.IntegerField(choices=[(0, 'DISABLED'), (10, 'MANUAL'), (20, 'COMMISSIONING'), (25, 'STANDBY'), (30, 'SCHEDULABLE')], default=0, help_text='<div><ul><li>DISABLED - this is what disabled means.</li>\n    <li>MANUAL - this is what manual means.</li>\n    <li>COMMISSIONING - this is what commissioning means.</li>\n    <li>STANDBY - this is what standby means.</li>\n    <li>SCHEDULABLE - this is what schedulable means.</li></ul></div>\n    '),
        ),
    ]
