# Generated by Django 3.0.7 on 2020-06-11 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0017_auto_20200521_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filterwheel',
            name='filters',
        ),
        migrations.RemoveField(
            model_name='mode',
            name='camera_type',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='filter_wheel',
        ),
        migrations.RemoveField(
            model_name='cameratype',
            name='acquire_processing_time',
        ),
        migrations.RemoveField(
            model_name='cameratype',
            name='default_mode',
        ),
        migrations.RemoveField(
            model_name='cameratype',
            name='filter_change_time',
        ),
        migrations.DeleteModel(
            name='Filter',
        ),
        migrations.DeleteModel(
            name='FilterWheel',
        ),
        migrations.DeleteModel(
            name='Mode',
        ),
    ]
