# Generated by Django 3.0.7 on 2020-06-17 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0019_merge_20200617_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericmode',
            name='params',
        ),
    ]
