# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_site_elevation'),
    ]

    operations = [
        migrations.AddField(
            model_name='telescope',
            name='ha_limit_neg',
            field=models.FloatField(default=4.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telescope',
            name='ha_limit_pos',
            field=models.FloatField(default=-4.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telescope',
            name='horizon',
            field=models.FloatField(default=15.0),
            preserve_default=False,
        ),
    ]
