# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 17:30
from __future__ import unicode_literals

from django.db import migrations


def populate_states(apps, schema_editor):
    Instrument = apps.get_model('hardware', 'Instrument')
    for i in Instrument.objects.all():
        i.state = 30 if i.schedulable else 10  # cannot use Instrument.ENABLED with apps.get_model
        i.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0004_instrument_state'),
    ]

    operations = [
        migrations.RunPython(populate_states),
    ]
