# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-25 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0014_cameratype_allow_self_guiding'),
    ]

    operations = [
        migrations.AddField(
            model_name='telescope',
            name='zenith_blind_spot',
            field=models.FloatField(default=0.0, help_text='For AltAz telescopes, radius of zenith blind spot in degrees'),
        ),
    ]
