# Generated by Django 3.0.6 on 2020-05-21 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0016_auto_20190814_0723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opticalelementgroup',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='cameratype',
            name='allow_self_guiding',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='cameratype',
            name='default_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hardware.Mode'),
        ),
        migrations.AlterField(
            model_name='genericmodegroup',
            name='default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default', to='hardware.GenericMode'),
        ),
        migrations.AlterField(
            model_name='genericmodegroup',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hardware.ModeType'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='state',
            field=models.IntegerField(choices=[(0, 'DISABLED'), (10, 'MANUAL'), (20, 'COMMISSIONING'), (25, 'STANDBY'), (30, 'SCHEDULABLE')], default=0, help_text='<div><ul><li>DISABLED - The instrument is in configdb, but does not physically exist or is sitting in a box somewhere.</li>\n    <li>MANUAL - The instrument is plugged in, but not ready to do any science.</li>\n    <li>COMMISSIONING - The instrument is currently commissioning, but should not yet be exposed to the network.</li>\n    <li>STANDBY - The instrument has been commissioned and is ready to be switched into SCHEDULABLE when needed.</li>\n    <li>SCHEDULABLE - The instrument is part of the network and is ready for normal operations</li></ul></div>\n    '),
        ),
        migrations.AlterField(
            model_name='opticalelementgroup',
            name='default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default', to='hardware.OpticalElement'),
        ),
    ]
