# Generated by Django 3.0.7 on 2020-06-17 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0018_auto_20200611_2125'),
        ('hardware', '0018_genericmode_validation_schema'),
    ]

    operations = [
    ]
