# Generated by Django 3.0.6 on 2020-06-30 00:25

from django.db import migrations

def forward(apps, schema_editor):
    CameraType = apps.get_model('hardware', 'CameraType')
    InstrumentType = apps.get_model('hardware', 'InstrumentType')
    Instrument = apps.get_model('hardware', 'Instrument')
    for instrument in Instrument.objects.all():
        instrument.science_cameras.add(instrument.science_camera)
        camera_type = instrument.science_camera.camera_type
        instrument_type, _ = InstrumentType.objects.get_or_create(
            name=camera_type.name,
            code=camera_type.code,
            fixed_overhead_per_exposure=camera_type.fixed_overhead_per_exposure,
            front_padding=camera_type.front_padding,
            config_change_time=camera_type.config_change_time,
            acquire_exposure_time=camera_type.acquire_exposure_time,
            configuration_types=camera_type.configuration_types,
            default_acceptability_threshold=camera_type.default_acceptability_threshold,
            allow_self_guiding=camera_type.allow_self_guiding
        )
        instrument.instrument_type = instrument_type
        instrument.save()

        for generic_mode_group in camera_type.mode_types.all():
            generic_mode_group.instrument_type = instrument_type
            generic_mode_group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0021_add_instrument_type'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
