# Generated by Django 3.0.6 on 2020-07-09 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0022_populate_instrument_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameratype',
            name='acquire_exposure_time',
        ),
        migrations.RemoveField(
            model_name='cameratype',
            name='allow_self_guiding',
        ),
        migrations.RemoveField(
            model_name='cameratype',
            name='config_change_time',
        ),
        migrations.RemoveField(
            model_name='cameratype',
            name='configuration_types',
        ),
        migrations.RemoveField(
            model_name='cameratype',
            name='default_acceptability_threshold',
        ),
        migrations.RemoveField(
            model_name='cameratype',
            name='fixed_overhead_per_exposure',
        ),
        migrations.RemoveField(
            model_name='cameratype',
            name='front_padding',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='science_camera',
        ),
        migrations.AlterUniqueTogether(
            name='genericmodegroup',
            unique_together={('instrument_type', 'type')},
        ),
        migrations.RemoveField(
            model_name='genericmodegroup',
            name='camera_type',
        ),
    ]
