# Generated by Django 3.0.6 on 2021-03-10 08:04

from django.db import migrations

TYPES_WITH_ACQUISITION_OFF = ['LAMP_FLAT', 'ARC', 'AUTO_FOCUS', 'NRES_BIAS', 'NRES_DARK', 'BIAS', 'DARK', 'SCRIPT']
TYPES_WITHOUT_OPTICAL_ELEMENTS = ['BIAS', 'DARK', 'SCRIPT']

def forward(apps, schema_editor):
    # Fill in the configuration_type_links from the existing configuration_types in each instrument_type
    InstrumentType = apps.get_model('hardware', 'InstrumentType')
    ConfigurationType = apps.get_model('hardware', 'ConfigurationType')
    ConfigurationTypeProperties = apps.get_model('hardware', 'ConfigurationTypeProperties')

    instrument_types = InstrumentType.objects.all()
    for instrument_type in instrument_types:
        # for each configuration_type, create a ConfigurationType and add it to configuration_type_links
        for configuration_type in instrument_type.configuration_types:
            config_type_model = ConfigurationType.objects.get_or_create(
                code=configuration_type,
                name=configuration_type
            )
            config_type_properties = ConfigurationTypeProperties.get_or_create(
                configuration_type=config_type_model,
                instrument_type=instrument_type,
                requires_optical_elements=configuration_type not in TYPES_WITHOUT_OPTICAL_ELEMENTS,
                force_acquisition_off=configuration_type in TYPES_WITH_ACQUISITION_OFF
            )


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0025_auto_20210310_0754'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
