# Generated by Django 3.0.6 on 2021-03-10 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0026_auto_20210310_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumenttype',
            name='configuration_types',
        ),
        migrations.RenameField(
            model_name='instrumenttype',
            old_name='configuration_types_links',
            new_name='configuration_types'
        ),
    ]
