# Generated by Django 4.0.3 on 2022-03-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0029_instrumenttype_default_configuration_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericmode',
            name='validation_schema',
            field=models.JSONField(blank=True, default=dict, help_text='A cerberus styled validation schema that will be used to validate the structure this mode applies to'),
        ),
        migrations.AlterField(
            model_name='instrumenttype',
            name='validation_schema',
            field=models.JSONField(blank=True, default=dict, help_text='Cerberus styled validation schema used to validate instrument configs using this instrument type'),
        ),
    ]
