# Generated by Django 4.0.3 on 2022-04-12 23:21

from django.db import migrations


def add_generic_mode_types(apps, schema_editor):
    ModeType = apps.get_model('hardware', 'ModeType')
    ModeType.objects.get_or_create(id='readout')
    ModeType.objects.get_or_create(id='guiding')
    ModeType.objects.get_or_create(id='acquisition')
    ModeType.objects.get_or_create(id='exposure')
    ModeType.objects.get_or_create(id='rotator')


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0030_alter_genericmode_validation_schema_and_more'),
    ]

    operations = [
        migrations.RunPython(add_generic_mode_types)
    ]
