# Generated by Django 4.0.3 on 2023-01-09 23:18

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0032_telescope_aperture_telescope_telescope_front_padding_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrument',
            old_name='state',
            new_name='state_int',
        ),
        migrations.AddField(
            model_name='instrument',
            name='state',
            field=models.CharField(choices=[('DISABLED', 'DISABLED'), ('MANUAL', 'MANUAL'), ('COMMISSIONING', 'COMMISSIONING'), ('STANDBY', 'STANDBY'), ('SCHEDULABLE', 'SCHEDULABLE')], default='DISABLED', help_text='<div><ul><li>DISABLED - The instrument is in configdb, but does not physically exist or is sitting in a box somewhere.</li>\n    <li>MANUAL - The instrument is plugged in, but not ready to do any science.</li>\n    <li>COMMISSIONING - The instrument is currently commissioning, but should not yet be exposed to the network.</li>\n    <li>STANDBY - The instrument has been commissioned and is ready to be switched into SCHEDULABLE when needed.</li>\n    <li>SCHEDULABLE - The instrument is part of the network and is ready for normal operations</li></ul></div>\n    ', max_length=50),
        )
    ]
