# Generated by Django 4.0.3 on 2023-02-23 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0034_copy_instrument_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationtypeproperties',
            name='default_exposure_time',
            field=models.FloatField(default=0, help_text='Default exposure time for this configuration type', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
