# Generated by Django 4.0.3 on 2023-02-22 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0034_copy_instrument_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumenttype',
            name='minimum_flat_exposure_time',
            field=models.FloatField(default=2, help_text='The minimum exposure time to use for for flat exposures with this instrument type.', validators=[django.core.validators.MinValueValidator(2)]),
        ),
    ]
